services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    ports:
      - 4317:4317 # OTLP gRPC receiver
    environment:
      - AZURE_MONITOR_CONNECTION_STRING=${AZURE_MONITOR_CONNECTION_STRING}
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OTLP_ENDPOINT=http://otel-collector:4317
    depends_on:
      - otel-collector

  load-generator:
    image: curlimages/curl:latest
    volumes:
      - ./load-generator.sh:/load-generator.sh
    environment:
      - API_ENDPOINT=http://app:8000
    command: sh /load-generator.sh
    depends_on:
      - app