receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
exporters:
  debug:
    verbosity: detailed
  azuremonitor:
    connection_string: ${AZURE_MONITOR_CONNECTION_STRING}
service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [debug, azuremonitor]
